title: 和歌山県串本町
description: 和歌山県串本町内でテイクアウトできるお店
data_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vRTClb4JMxokKD4F1tLjlSOhHF62hYLbn3U4u9cvTBDhFR9ErPHLG5pYsOqdZmnu_O1ISi9t1u5F9DL/pub?gid=0&single=true&output=csv

map:
  lng: 135.7815
  lat: 33.4725
  zoom: 14

social:
  github: https://github.com/iemeshi/app
